### ISSUE TITLE
Search result page cannot display article properly.

### ISSUE THREAD

**Issue by anchovYu** [sjtu-meow/iOS#6]
The cell height is too small for all words to fit in.

**Comment by anchovYu** [comment]
wontfix (??)

**Comment by vinx13** [comment]
😊

**Comment by anchovYu** [comment]
Sent you a polite and embarrassed smile :))))))))))))))))))

**Comment by gousaiyang** [comment]
In fact we need to limit all content lengths in the backend APIs (more friendly if also on frondend App).
Currently the best solution might be limiting content lengths in our mock data so as not to break the display on the App.

**Comment by anchovYu** [comment]
Emmmm, not talking about multiple lines. A single line cannot fit in ..

**Comment by anchovYu** [comment]
![image](https://user-images.githubusercontent.com/25225043/30277514-9d3d0754-973a-11e7-9a98-ea5d6bf84d15.png)
See this.
