### ISSUE TITLE
Article banner picture are the same. Any modifications? Or could you please state the settings behind?

### ISSUE THREAD

**Issue by anchovYu** [sjtu-meow/iOS#8]
Emmm, at least, banner pics should be different, right?

There's no possibility that we retrieve banner pic from user chosen pics in article(like the first pic in article), is there?

**Comment by vinx13** [comment]
Selecting cover images on iOS is not supported, so default images are used if articles are posted from the App.

**Comment by anchovYu** [comment]
Could we at least choose different covers..?

**Comment by vinx13** [comment]
@anchovYu Could u fix that? 😊

**Comment by anchovYu** [comment]
:( Not familiar with those settings.

**Comment by vinx13** [comment]
@gousaiyang 
Replacing cover image`None` with some actual images in backend would be good.

**Comment by gousaiyang** [comment]
@TerCZ Could we have several different cat pictures stored into static resource folder to serve as placeholder covers? If no cover URL has been specified in an article posted by the client, the server can randomly choose one of those placeholder covers to improve the display on the App.

**Comment by chuzhe-as-a-dev** [comment]
Articles posted from iOS now have default cover.
